# Generated by Django 5.2.6 on 2025-09-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalcare', '0002_moodslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodslider',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
