# Generated by Django 5.2.6 on 2025-09-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helpline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('mental', 'Mental Health'), ('suicide', 'Suicide Prevention'), ('child', 'Child Helpline'), ('lgbtq', 'LGBTQ+ Support'), ('other', 'Other')], default='other', max_length=50)),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
